### ISSUE TITLE
Error while installing requirements.txt

### ISSUE THREAD

**Issue by Hack4Life** [liveblog/liveblog#1110]
Running `pip install -r requirements.txt` exits with the following error:

> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-rHV8T4/websockets/

Output of the install command: 

> root@ubuntu-2gb-nbg1-dc3-1 /var/www/liveblog/server # pip install -r requirements.txt
> Collecting gunicorn==19.3.0 (from -r requirements.txt (line 1))
>   Using cached gunicorn-19.3.0-py2.py3-none-any.whl
> Collecting honcho==0.7.1 (from -r requirements.txt (line 2))
>   Using cached honcho-0.7.1-py2.py3-none-any.whl
> Collecting Flask==0.10.1 (from -r requirements.txt (line 3))
>   Using cached Flask-0.10.1.tar.gz
> Collecting Flask-Cache==0.13.1 (from -r requirements.txt (line 4))
>   Using cached Flask-Cache-0.13.1.tar.gz
> Collecting Flask-Cors==2.1.0 (from -r requirements.txt (line 5))
>   Using cached Flask-Cors-2.1.0.tar.gz
> Collecting Flask-S3==0.1.7 (from -r requirements.txt (line 6))
>   Using cached Flask-S3-0.1.7.tar.gz
> Collecting html5lib==0.999999999 (from -r requirements.txt (line 7))
>   Using cached html5lib-0.999999999-py2.py3-none-any.whl
> Obtaining Superdesk-Core from git+git://github.com/superdesk/superdesk-core.git@v1.6.3#egg=Superdesk-Core (from -r requirements.txt (line 10))
>   Updating ./src/superdesk-core clone (to v1.6.3)
> Collecting Werkzeug>=0.7 (from Flask==0.10.1->-r requirements.txt (line 3))
>   Using cached Werkzeug-0.14.1-py2.py3-none-any.whl
> Collecting Jinja2>=2.4 (from Flask==0.10.1->-r requirements.txt (line 3))
>   Using cached Jinja2-2.10-py2.py3-none-any.whl
> Collecting itsdangerous>=0.21 (from Flask==0.10.1->-r requirements.txt (line 3))
>   Using cached itsdangerous-0.24.tar.gz
> Collecting Six (from Flask-Cors==2.1.0->-r requirements.txt (line 5))
>   Using cached six-1.11.0-py2.py3-none-any.whl
> Collecting Boto>=2.5.2 (from Flask-S3==0.1.7->-r requirements.txt (line 6))
>   Using cached boto-2.48.0-py2.py3-none-any.whl
> Collecting webencodings (from html5lib==0.999999999->-r requirements.txt (line 7))
>   Using cached webencodings-0.5.1-py2.py3-none-any.whl
> Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python2.7/dist-packages (from html5lib==0.999999999->-r requirements.txt (line 7))
> Collecting eve<0.7,>=0.6 (from Superdesk-Core->-r requirements.txt (line 10))
>   Using cached Eve-0.6.4.tar.gz
> Collecting eve-elastic<0.7,>=0.5.2 (from Superdesk-Core->-r requirements.txt (line 10))
>   Using cached Eve_Elastic-0.6-py2.py3-none-any.whl
> Collecting elasticsearch<2.0,>=1.9.0 (from Superdesk-Core->-r requirements.txt (line 10))
>   Using cached elasticsearch-1.9.0-py2.py3-none-any.whl
> Collecting flask-mail<0.10,>=0.9 (from Superdesk-Core->-r requirements.txt (line 10))
>   Using cached Flask-Mail-0.9.1.tar.gz
> Collecting flask-script<3.0,>=2.0.5 (from Superdesk-Core->-r requirements.txt (line 10))
>   Using cached Flask-Script-2.0.6.tar.gz
> Collecting flask-sentinel<0.1,>=0.0.4 (from Superdesk-Core->-r requirements.txt (line 10))
>   Using cached Flask-Sentinel-0.0.7.tar.gz
> Collecting flask-oauthlib<0.10,>=0.9.1 (from Superdesk-Core->-r requirements.txt (line 10))
>   Using cached Flask_OAuthlib-0.9.4-py2-none-any.whl
> Collecting pillow<3.5,>=3.0 (from Superdesk-Core->-r requirements.txt (line 10))
>   Using cached Pillow-3.4.2-cp27-cp27mu-manylinux1_x86_64.whl
> Collecting arrow<0.9,>=0.4 (from Superdesk-Core->-r requirements.txt (line 10))
>   Using cached arrow-0.8.0.tar.gz
> Collecting asyncio<3.5,>=3.4 (from Superdesk-Core->-r requirements.txt (line 10))
>   Using cached asyncio-3.4.3.tar.gz
> Collecting bcrypt<3.2,>=3.1.1 (from Superdesk-Core->-r requirements.txt (line 10))
>   Using cached bcrypt-3.1.4-cp27-cp27mu-manylinux1_x86_64.whl
> Collecting beautifulsoup4<4.6,>=4.4 (from Superdesk-Core->-r requirements.txt (line 10))
>   Using cached beautifulsoup4-4.5.3-py2-none-any.whl
> Collecting blinker<1.5,>=1.3 (from Superdesk-Core->-r requirements.txt (line 10))
>   Using cached blinker-1.4.tar.gz
> Collecting celery[redis]<4.1,>=4.0.2 (from Superdesk-Core->-r requirements.txt (line 10))
>   Using cached celery-4.0.2-py2.py3-none-any.whl
> Collecting feedparser<5.3,>=5.2 (from Superdesk-Core->-r requirements.txt (line 10))
>   Using cached feedparser-5.2.1.zip
> Collecting hachoir3-superdesk<3.1,>=3.0a1 (from Superdesk-Core->-r requirements.txt (line 10))
>   Using cached hachoir3-superdesk-3.0a1.post2.tar.gz
> Collecting HermesCache<0.7.0,>=0.6.0 (from Superdesk-Core->-r requirements.txt (line 10))
>   Using cached HermesCache-0.6.1.tar.gz
> Collecting python-magic<0.5,>=0.4 (from Superdesk-Core->-r requirements.txt (line 10))
>   Using cached python_magic-0.4.15-py2.py3-none-any.whl
> Collecting python3-ldap<0.9.9,>=0.9.8 (from Superdesk-Core->-r requirements.txt (line 10))
>   Using cached python3_ldap-0.9.8.4-py2.py3-none-any.whl
> Collecting pytz>=2015.4 (from Superdesk-Core->-r requirements.txt (line 10))
>   Using cached pytz-2018.3-py2.py3-none-any.whl
> Collecting tzlocal<1.4,>=1.2.2 (from Superdesk-Core->-r requirements.txt (line 10))
>   Using cached tzlocal-1.3.2.tar.gz
> Collecting raven[flask]<6.0,>=5.10 (from Superdesk-Core->-r requirements.txt (line 10))
>   Using cached raven-5.33.0-py2.py3-none-any.whl
> Collecting requests<2.13,>=2.7.0 (from Superdesk-Core->-r requirements.txt (line 10))
>   Using cached requests-2.12.5-py2.py3-none-any.whl
> Collecting statsd<3.3,>=3.1 (from Superdesk-Core->-r requirements.txt (line 10))
>   Using cached statsd-3.2.2-py2.py3-none-any.whl
> Collecting httmock<1.3,>=1.2.3 (from Superdesk-Core->-r requirements.txt (line 10))
>   Using cached httmock-1.2.6.tar.gz
> Collecting boto3<1.5,>=1.1.4 (from Superdesk-Core->-r requirements.txt (line 10))
>   Using cached boto3-1.4.8-py2.py3-none-any.whl
> Collecting websockets<3.3,>=3.0 (from Superdesk-Core->-r requirements.txt (line 10))
>   Using cached websockets-3.2.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-rHV8T4/websockets/setup.py", line 19, in <module>
>         with open(os.path.join(root, 'README'), encoding='utf-8') as f:
>     TypeError: 'encoding' is an invalid keyword argument for this function

I'm running ubuntu 16.04.

**Comment by eos87** [comment]
Hi @Hack4Life, you're using python 3, right? It seems like a not compatible websockets dependency issue.

**Comment by Hack4Life** [comment]
`python -V` returns  `Python 2.7.12`. `python3` is also installed in version `3.5.2`

Also pip triggers python 2.7.12 and not python3:
`pip -V
pip 9.0.3 from /home/fabian/.local/lib/python2.7/site-packages (python 2.7)`

Here is the content of my pip file (in `/home/fabian/.local/bin/pip`):
`#!/usr/bin/python

# -*- coding: utf-8 -*-
import re
import sys

from pip import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())`

**Comment by GyanP** [comment]
Hi @Hack4Life 
Please install Python 3.6.3 create virtual enviroment with using Python3 with command:
"virtualenv -p python3 env"

**Comment by BobZteD** [comment]
Hi 
i'm very new on this. when i try to install i get error on this step "pip install -r requirements.txt" it's looklike there is no requirements.txt anywhere!

"(env) root@LiveBlog:~/env/lib/python3.5# pip install -r requirements.txt
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'"

i also tried this outside Venv but result was same...

could you please help me

Thanks

**Comment by eos87** [comment]
Hi @BobZteD, you have to run that command within `liveblog/server/` folder.
