### ISSUE TITLE
Embed Code Not Available

### ISSUE THREAD

**Issue by rehmatworks** [liveblog/liveblog#1263]
I used docker installation method to set Live Blog on my client's server. After spending several hours, at last I got this working fine but embed code for blogs isn't available. In a forum post, I read that we need to set Amazon keys in order to get embed code working. Can anyone please elaborate what kind of configuration is needed? Any help will be highly appreciated.

**Comment by eos87** [comment]
Hi @rehmatworks, perhaps this is the configuration that was meant in the forum https://github.com/liveblog/liveblog/blob/master/AMAZON-S3-PUBLISHED-URL.MD 

I haven't personally worked with the docker installation method and I would say it's pretty outdated. Hopefully in future releases we will be able to update the instructions for docker. Nonetheless, if you feel like providing a PR for it is also more than welcome :)
