### ISSUE TITLE
Make privacyStatus customizable

### ISSUE THREAD

**Issue by cbieser** [liveblog/liveblog#1270]
Unfortunately the the privacyStatus ist hard coded.

https://github.com/liveblog/liveblog/blob/199077d0fe0fa45e3acdfc14cdac055126c483f2/client/app/scripts/sir-trevor-blocks/video-block.js#L160 

Please make it customizable as we need `unlisted`. 

Valid values for this property are:
* `private`
* `public`
* `unlisted`

**Comment by eos87** [comment]
Hi @cbieser. Yeah, the direct video upload to youtube is in beta version that's why it was hardcoded. I will discuss this internally to see if we can make this customizable and put it in one of the upcoming releases (or maybe next release, who knows). On the other hand, if you feel like providing an improvement for this you're more than welcome. Thanks.

**Comment by cbieser** [comment]
Hi @eos87, what do you think of something like that?
> client/webpack.config.js
> @@ -291,6 +291,15 @@ const configLiveblog = (grunt) => ({
> ```
>     embedly: {
>         key: grunt.option('embedly-key') || process.env.EMBEDLY_KEY || ''
>     },
>     youtube: {
>         snippet: {
>             tags: grunt.option('youtube-snippet-tags') || process.env.YOUTUBE_SNIPPET_TAGS || ['youtube-cors-upload'],
>             categoryId: grunt.option('youtube-snippet-categoryId') || process.env.YOUTUBE_SNIPPET_CATEGORYID || 22
>         },
>         status: {
>             privacyStatus: grunt.option('youtube-status-privacyStatus') || process.env.YOUTUBE_STATUS_PRIVACYSTATUS || 'public'
>         }
>     },
>     facebookAppId: grunt.option('facebook-appid') || process.env.FACEBOOK_APP_ID || '',
>     syndication: process.env.SYNDICATION || false,
>     marketplace: process.env.MARKETPLACE || false,
> 
> ```

**Comment by eos87** [comment]
Hi @cbieser. Thanks for the suggestion. This is a good start but it will need more coding in some other parts. For now, I just changed the value to `unlisted` and it should be released with `v3.6.7` very soon. We will implement a way to handle the privacy status from the settings in next release if possible.

**Comment by eos87** [comment]
This has been addressed on v3.7.0.
