### ISSUE TITLE
How to create Live Blog 

### ISSUE THREAD

**Issue by okupdatenumber** [liveblog/liveblog#1282]
I am using WordPress. ( Digital Ocean Ubuntu 18.04) . How to setup live Blog. Please Provide Complete Process. Dear friends, just tell me how to set this .

**Comment by eos87** [comment]
Hi @okupdatenumber, just look at the [Reame](https://github.com/liveblog/liveblog/blob/master/README.md) file. There is also another for [Mac OS](https://github.com/liveblog/liveblog/blob/master/README-macos.md)

If you're looking for managed hosting can go to https://liveblog.pro
