### ISSUE TITLE
Running client server throws error

### ISSUE THREAD

**Issue by Hack4Life** [liveblog/liveblog#1311]
Walking through the readme on a fresh Ubuntu 16.04 installation fails on the [startup of the client server](https://github.com/liveblog/liveblog#configure-the-client).

The following command causes the problem:
`grunt --force server --server='http://localhost:5000/api' --ws='ws://localhost:5100' `

```
ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./node_modules/superdesk-core/scripts/apps/authoring/styles/multiedit.scss
Module build failed: Error: ENOENT: no such file or directory, scandir '/home/user/Desktop/liveblog-master/client/node_modules/node-sass/vendor'
```

The full output of the command is in this ghostbin available: [https://ghostbin.co/paste/fff9j](https://ghostbin.co/paste/fff9j)

Starting the server within the python virtual environment in another terminal window worked fine without any errors and is still running in the background: `honcho -f ../docker/Procfile-dev start `

Is the [README.md](https://github.com/liveblog/liveblog/blob/master/README.md) outdated or what could cause this issue? 

Downloaded version 3.8.1

**Comment by eos87** [comment]
Hi @Hack4Life. This seems to be an issue of node-sass and npm. Check this https://github.com/sass/node-sass/issues/1579#issuecomment-227661284 I hope it helps.
