### ISSUE TITLE
Server won't start and old Docker image

### ISSUE THREAD

**Issue by kobinet-nachrichten** [liveblog/liveblog#1317]
Hi there,

we want to run an liveblog-instance for testing-purposes, but it wont work. I followed the instructions exactly, but when i want to start the server with honcho, it dies with "wamp.1 stopped", followed by "beat.1 stopped" and "rest.1 stopped". No error message. The client server starts without problems (but isn't usable without the server...). I tried to start the Docker-Image, which worked nice, but it is an very old version of liveblog. 

My questions are: 
Do you have any idea, why the server dies?
Can you provide an Docker image with the current version of Liveblog?

Thanks for your help in advance
Tom

**Comment by eos87** [comment]
Hello there. Sorry for the very belated reply. For the time being, we're not planning to add the support for Docker, perhaps in the future (later in the year). Nevertheless, as you know Liveblog is an Open Source project so if you're willing to contribute in this regards you're more than welcome. I'll be glad to review any PR
