### ISSUE TITLE
Updated version of the install process

### ISSUE THREAD

**Issue by agenceKanvas** [liveblog/liveblog#1323]
Hi !!!
First, many thanks for the hard work. 

I need to install Liveblog for my website but I can't get to get it to work. 
I've followed both ways and for each I had troubles getting it to even finish installing. 

Can you please add more info about the first method ? I think it is a little outdated :
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
Node 6.X is not maintained anymore. 

And if you add some infos on how to setup the production version that would be awesome. 

Thanks a lot !

Best regards

**Comment by agenceKanvas** [comment]
This is the kind of error I get : 

ERROR: Requested docutils>=0.10 from https://files.pythonhosted.org/packages/d4/12/6c3fd74a590c7327c98cae008c11d536029fa9cd7924de477e8cb8804186/docutils-0.15.1-post1.tar.gz#sha256=f33ddb723332c6d6b6d99731ee1fc0c35eb4044a2df5cca1c64c8aa78eaf22cb (from botocore<1.9.0,>=1.8.50->boto3<1.6,>=1.1.4->Superdesk-Core->-r requirements.txt (line 16)) has different version in metadata: '0.15.1'

**Comment by eos87** [comment]
Hi @agenceKanvas, I've updated the installation instructions in the readme file. Liveblog is fully compatible with Nodejs v10 which can be installed like following:
```
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt-get install nodejs
```
Please have another look at the [readme](../blob/master/README.md#install-the-dependencies-for-mac-os-users-follow-this) file. Also my comments on #1324 could help, I think both issues are the same. 

Have a good one!

**Comment by agenceKanvas** [comment]
Thank you so much for your help @eos87 !
It's much better BUT I still have problem. 
I think that for the server isntall it's ok. Now the problem is coming from the client part.

This is the erreor :

(env) root@liveblog:~/liveblog/client# sudo npm install
loadDep:superdesk-core →  ▌ ╢███████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm WARN deprecated jquery-jcrop@0.9.13: No further updates will be released for this pacakge after v0.9.15. Original creator has not released any new versions in 2+ years, as of Aug 1, 2020 (See https://github.com/tapmodo/Jcrop). Updating this package is not easy due to original creator's package structure. If futher assistnace is needed, reach out to original creator or https://www.npmjs.com/~jengland
npm WARN deprecated eslint-loader@2.2.1: This loader has been deprecated. Please use eslint-webpack-plugin
loadDep:superdesk-core →  ▐ ╢███████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm ERR! Linux 4.15.0-121-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/liveblog/client/npm-debug.log
(env) root@liveblog:~/liveblog/client#

It's the "npm install" that is causing problem. I tried also with sudo npm install, same error.

**Comment by eos87** [comment]
Hi @agenceKanvas, unfortunately I have no clue on this one. Maybe if you attach this file `/root/liveblog/client/npm-debug.log` I might be able to figure out what's going on there.

**Comment by agenceKanvas** [comment]
Hi @eos87 !
The last lines are here : 

3264 verbose headers   vary: 'Accept-Encoding',
3264 verbose headers   'cf-cache-status': 'HIT',
3264 verbose headers   'cf-request-id': '0783e8e09c0000d6e9a40de000000001',
3264 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
3264 verbose headers   server: 'cloudflare' }
3265 silly get cb [ 304,
3265 silly get   { date: 'Fri, 08 Jan 2021 14:04:08 GMT',
3265 silly get     connection: 'keep-alive',
3265 silly get     'set-cookie':
3265 silly get      [ '__cfduid=d57a7f6a693decc43425a2c1f7ed4311b1610114648; expires=Sun, 07-Feb-21 14:04:08 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
3265 silly get     'cf-ray': '60e6774768aed6e9-FRA',
3265 silly get     age: '2505',
3265 silly get     'cache-control': 'public, max-age=300',
3265 silly get     etag: '"1bbc22003f5f33b87752cad0f1f84767"',
3265 silly get     'last-modified': 'Sat, 22 Aug 2020 20:43:11 GMT',
3265 silly get     vary: 'Accept-Encoding',
3265 silly get     'cf-cache-status': 'HIT',
3265 silly get     'cf-request-id': '0783e8e09c0000d6e9a40de000000001',
3265 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
3265 silly get     server: 'cloudflare' } ]
3266 verbose etag https://registry.npmjs.org/parse-json from cache
3267 verbose get saving parse-json to /root/.npm/registry.npmjs.org/parse-json/.cache.json
3268 silly resolveWithNewModule parse-json@5.1.0 checking installable status
3269 silly cache add args [ 'parse-json@^5.0.0', null ]
3270 verbose cache add spec parse-json@^5.0.0
3271 silly cache add parsed spec Result {
3271 silly cache add   raw: 'parse-json@^5.0.0',
3271 silly cache add   scope: null,
3271 silly cache add   name: 'parse-json',
3271 silly cache add   rawSpec: '^5.0.0',
3271 silly cache add   spec: '>=5.0.0 <6.0.0',
3271 silly cache add   type: 'range' }
3272 silly addNamed parse-json@>=5.0.0 <6.0.0
3273 verbose addNamed ">=5.0.0 <6.0.0" is a valid semver range for parse-json
3274 silly addNameRange { name: 'parse-json', range: '>=5.0.0 <6.0.0', hasData: false }
3275 silly mapToRegistry name parse-json
3276 silly mapToRegistry using default registry
3277 silly mapToRegistry registry https://registry.npmjs.org/
3278 silly mapToRegistry uri https://registry.npmjs.org/parse-json
3279 verbose addNameRange registry:https://registry.npmjs.org/parse-json not in flight; fetching
3280 http 304 https://registry.npmjs.org/import-fresh
3281 verbose headers { date: 'Fri, 08 Jan 2021 14:04:08 GMT',
3281 verbose headers   connection: 'keep-alive',
3281 verbose headers   'set-cookie':
3281 verbose headers    [ '__cfduid=d5381546dc233733e9a75831f5489926c1610114648; expires=Sun, 07-Feb-21 14:04:08 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
3281 verbose headers   'cf-ray': '60e677476c8e97c0-FRA',
3281 verbose headers   age: '4835',
3281 verbose headers   'cache-control': 'public, max-age=300',
3281 verbose headers   etag: '"82bd14b0677475e6d6bab906d253542e"',
3281 verbose headers   'last-modified': 'Sun, 20 Dec 2020 13:35:44 GMT',
3281 verbose headers   vary: 'Accept-Encoding',
3281 verbose headers   'cf-cache-status': 'HIT',
3281 verbose headers   'cf-request-id': '0783e8e09c000097c02833a000000001',
3281 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
3281 verbose headers   server: 'cloudflare' }
3282 silly get cb [ 304,
3282 silly get   { date: 'Fri, 08 Jan 2021 14:04:08 GMT',
3282 silly get     connection: 'keep-alive',
3282 silly get     'set-cookie':
3282 silly get      [ '__cfduid=d5381546dc233733e9a75831f5489926c1610114648; expires=Sun, 07-Feb-21 14:04:08 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
3282 silly get     'cf-ray': '60e677476c8e97c0-FRA',
3282 silly get     age: '4835',
3282 silly get     'cache-control': 'public, max-age=300',
3282 silly get     etag: '"82bd14b0677475e6d6bab906d253542e"',
3282 silly get     'last-modified': 'Sun, 20 Dec 2020 13:35:44 GMT',
3282 silly get     vary: 'Accept-Encoding',
3282 silly get     'cf-cache-status': 'HIT',
3282 silly get     'cf-request-id': '0783e8e09c000097c02833a000000001',
3282 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
3282 silly get     server: 'cloudflare' } ]
3283 verbose etag https://registry.npmjs.org/import-fresh from cache
3284 verbose get saving import-fresh to /root/.npm/registry.npmjs.org/import-fresh/.cache.json
3285 http 304 https://registry.npmjs.org/path-type
3286 verbose headers { date: 'Fri, 08 Jan 2021 14:04:08 GMT',
3286 verbose headers   connection: 'keep-alive',
3286 verbose headers   'set-cookie':
3286 verbose headers    [ '__cfduid=dccf9cb43d24159d867faf9ee17ef3aa61610114648; expires=Sun, 07-Feb-21 14:04:08 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
3286 verbose headers   'cf-ray': '60e67747683fd6fd-FRA',
3286 verbose headers   age: '6578',
3286 verbose headers   'cache-control': 'public, max-age=300',
3286 verbose headers   etag: '"3857a893cf1a7e9fefbc1b42e44dfb87"',
3286 verbose headers   'last-modified': 'Tue, 12 Mar 2019 09:25:22 GMT',
3286 verbose headers   vary: 'Accept-Encoding',
3286 verbose headers   'cf-cache-status': 'HIT',
3286 verbose headers   'cf-request-id': '0783e8e09f0000d6fdbe29b000000001',
3286 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
3286 verbose headers   server: 'cloudflare' }
3287 silly get cb [ 304,
3287 silly get   { date: 'Fri, 08 Jan 2021 14:04:08 GMT',
3287 silly get     connection: 'keep-alive',
3287 silly get     'set-cookie':
3287 silly get      [ '__cfduid=dccf9cb43d24159d867faf9ee17ef3aa61610114648; expires=Sun, 07-Feb-21 14:04:08 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
3287 silly get     'cf-ray': '60e67747683fd6fd-FRA',
3287 silly get     age: '6578',
3287 silly get     'cache-control': 'public, max-age=300',
3287 silly get     etag: '"3857a893cf1a7e9fefbc1b42e44dfb87"',
3287 silly get     'last-modified': 'Tue, 12 Mar 2019 09:25:22 GMT',
3287 silly get     vary: 'Accept-Encoding',
3287 silly get     'cf-cache-status': 'HIT',
3287 silly get     'cf-request-id': '0783e8e09f0000d6fdbe29b000000001',
3287 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
3287 silly get     server: 'cloudflare' } ]
3288 verbose etag https://registry.npmjs.org/path-type from cache
3289 verbose get saving path-type to /root/.npm/registry.npmjs.org/path-type/.cache.json
3290 http 304 https://registry.npmjs.org/yaml
3291 verbose headers { date: 'Fri, 08 Jan 2021 14:04:08 GMT',
3291 verbose headers   connection: 'keep-alive',
3291 verbose headers   'set-cookie':
3291 verbose headers    [ '__cfduid=d02a24917c01f4b8eb9633943cc0d1d241610114648; expires=Sun, 07-Feb-21 14:04:08 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
3291 verbose headers   'cf-ray': '60e677476fc41f25-FRA',
3291 verbose headers   age: '6709',
3291 verbose headers   'cache-control': 'public, max-age=300',
3291 verbose headers   etag: '"46b1d1df83070eff35d1f062ea343b71"',
3291 verbose headers   'last-modified': 'Mon, 05 Oct 2020 22:31:55 GMT',
3291 verbose headers   vary: 'Accept-Encoding',
3291 verbose headers   'cf-cache-status': 'HIT',
3291 verbose headers   'cf-request-id': '0783e8e0a300001f259981e000000001',
3291 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
3291 verbose headers   server: 'cloudflare' }
3292 silly get cb [ 304,
3292 silly get   { date: 'Fri, 08 Jan 2021 14:04:08 GMT',
3292 silly get     connection: 'keep-alive',
3292 silly get     'set-cookie':
3292 silly get      [ '__cfduid=d02a24917c01f4b8eb9633943cc0d1d241610114648; expires=Sun, 07-Feb-21 14:04:08 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
3292 silly get     'cf-ray': '60e677476fc41f25-FRA',
3292 silly get     age: '6709',
3292 silly get     'cache-control': 'public, max-age=300',
3292 silly get     etag: '"46b1d1df83070eff35d1f062ea343b71"',
3292 silly get     'last-modified': 'Mon, 05 Oct 2020 22:31:55 GMT',
3292 silly get     vary: 'Accept-Encoding',
3292 silly get     'cf-cache-status': 'HIT',
3292 silly get     'cf-request-id': '0783e8e0a300001f259981e000000001',
3292 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
3292 silly get     server: 'cloudflare' } ]
3293 verbose etag https://registry.npmjs.org/yaml from cache
3294 verbose get saving yaml to /root/.npm/registry.npmjs.org/yaml/.cache.json
3295 http 304 https://registry.npmjs.org/@types%2fparse-json
3296 verbose headers { date: 'Fri, 08 Jan 2021 14:04:08 GMT',
3296 verbose headers   connection: 'keep-alive',
3296 verbose headers   'set-cookie':
3296 verbose headers    [ '__cfduid=deabac3ade5240c137f912e29e92c4fa21610114648; expires=Sun, 07-Feb-21 14:04:08 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
3296 verbose headers   'cf-ray': '60e677475b73dfe7-FRA',
3296 verbose headers   age: '503',
3296 verbose headers   'cache-control': 'public, max-age=300',
3296 verbose headers   etag: '"2735d6278f40d20ffa8145948fdd1b11"',
3296 verbose headers   'last-modified': 'Mon, 14 Dec 2020 09:18:23 GMT',
3296 verbose headers   vary: 'Accept-Encoding',
3296 verbose headers   'cf-cache-status': 'HIT',
3296 verbose headers   'cf-request-id': '0783e8e09c0000dfe71ebc4000000001',
3296 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
3296 verbose headers   server: 'cloudflare' }
3297 silly get cb [ 304,
3297 silly get   { date: 'Fri, 08 Jan 2021 14:04:08 GMT',
3297 silly get     connection: 'keep-alive',
3297 silly get     'set-cookie':
3297 silly get      [ '__cfduid=deabac3ade5240c137f912e29e92c4fa21610114648; expires=Sun, 07-Feb-21 14:04:08 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
3297 silly get     'cf-ray': '60e677475b73dfe7-FRA',
3297 silly get     age: '503',
3297 silly get     'cache-control': 'public, max-age=300',
3297 silly get     etag: '"2735d6278f40d20ffa8145948fdd1b11"',
3297 silly get     'last-modified': 'Mon, 14 Dec 2020 09:18:23 GMT',
3297 silly get     vary: 'Accept-Encoding',
3297 silly get     'cf-cache-status': 'HIT',
3297 silly get     'cf-request-id': '0783e8e09c0000dfe71ebc4000000001',
3297 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
3297 silly get     server: 'cloudflare' } ]
3298 verbose etag https://registry.npmjs.org/@types%2fparse-json from cache
3299 verbose get saving @types/parse-json to /root/.npm/registry.npmjs.org/_40types_252fparse-json/.cache.json
3300 verbose get https://registry.npmjs.org/parse-json not expired, no request
3301 silly addNameRange number 2 { name: 'parse-json', range: '>=5.0.0 <6.0.0', hasData: true }
3302 silly addNameRange versions [ 'parse-json',
3302 silly addNameRange   [ '1.0.0',
3302 silly addNameRange     '1.0.1',
3302 silly addNameRange     '2.0.0',
3302 silly addNameRange     '2.1.0',
3302 silly addNameRange     '2.2.0',
3302 silly addNameRange     '3.0.0',
3302 silly addNameRange     '4.0.0',
3302 silly addNameRange     '5.0.0',
3302 silly addNameRange     '5.0.1',
3302 silly addNameRange     '5.1.0' ] ]
3303 silly addNamed parse-json@5.1.0
3304 verbose addNamed "5.1.0" is a plain semver version for parse-json
3305 silly resolveWithNewModule import-fresh@3.3.0 checking installable status
3306 silly cache add args [ 'import-fresh@^3.1.0', null ]
3307 verbose cache add spec import-fresh@^3.1.0
3308 silly cache add parsed spec Result {
3308 silly cache add   raw: 'import-fresh@^3.1.0',
3308 silly cache add   scope: null,
3308 silly cache add   name: 'import-fresh',
3308 silly cache add   rawSpec: '^3.1.0',
3308 silly cache add   spec: '>=3.1.0 <4.0.0',
3308 silly cache add   type: 'range' }
3309 silly addNamed import-fresh@>=3.1.0 <4.0.0
3310 verbose addNamed ">=3.1.0 <4.0.0" is a valid semver range for import-fresh
3311 silly addNameRange { name: 'import-fresh', range: '>=3.1.0 <4.0.0', hasData: false }
3312 silly mapToRegistry name import-fresh
3313 silly mapToRegistry using default registry
3314 silly mapToRegistry registry https://registry.npmjs.org/
3315 silly mapToRegistry uri https://registry.npmjs.org/import-fresh
3316 verbose addNameRange registry:https://registry.npmjs.org/import-fresh not in flight; fetching
3317 silly resolveWithNewModule path-type@4.0.0 checking installable status
3318 silly cache add args [ 'path-type@^4.0.0', null ]
3319 verbose cache add spec path-type@^4.0.0
3320 silly cache add parsed spec Result {
3320 silly cache add   raw: 'path-type@^4.0.0',
3320 silly cache add   scope: null,
3320 silly cache add   name: 'path-type',
3320 silly cache add   rawSpec: '^4.0.0',
3320 silly cache add   spec: '>=4.0.0 <5.0.0',
3320 silly cache add   type: 'range' }
3321 silly addNamed path-type@>=4.0.0 <5.0.0
3322 verbose addNamed ">=4.0.0 <5.0.0" is a valid semver range for path-type
3323 silly addNameRange { name: 'path-type', range: '>=4.0.0 <5.0.0', hasData: false }
3324 silly mapToRegistry name path-type
3325 silly mapToRegistry using default registry
3326 silly mapToRegistry registry https://registry.npmjs.org/
3327 silly mapToRegistry uri https://registry.npmjs.org/path-type
3328 verbose addNameRange registry:https://registry.npmjs.org/path-type not in flight; fetching
3329 verbose stack Error: Missing required argument #1
3329 verbose stack     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
3329 verbose stack     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
3329 verbose stack     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
3329 verbose stack     at /usr/share/npm/lib/install/deps.js:457:7
3329 verbose stack     at /usr/share/npm/node_modules/iferr/index.js:13:50
3329 verbose stack     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
3329 verbose stack     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
3329 verbose stack     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
3329 verbose stack     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
3329 verbose stack     at /usr/share/npm/node_modules/iferr/index.js:13:50
3330 verbose cwd /root/liveblog/client
3331 error Linux 4.15.0-121-generic
3332 error argv "/usr/bin/node" "/usr/bin/npm" "install"
3333 error node v8.10.0
3334 error npm  v3.5.2
3335 error code EMISSINGARG
3336 error typeerror Error: Missing required argument #1
3336 error typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
3336 error typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
3336 error typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
3336 error typeerror     at /usr/share/npm/lib/install/deps.js:457:7
3336 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
3336 error typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
3336 error typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
3336 error typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
3336 error typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
3336 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
3337 error typeerror This is an error with npm itself. Please report this error at:
3337 error typeerror     <http://github.com/npm/npm/issues>
3338 verbose exit [ 1, true ]

**Comment by eos87** [comment]
I really have no clue on this one. I would install node `v10.x`, remove the `node_modules` folder and try the `npm install` once more.

**Comment by agenceKanvas** [comment]
Ah ah no problem @eos87 :) I re-installed everything and I think I'm getting something. 
Now I tried to run the client in production mode, and I've ran a reverse proxy on localhost. 
You can see the result here : http://liveblog.exprime.media
I have a LOT of errors, probably because of me. I have to setup the real URL in a config file right ? I just haven't found which one :D

**Comment by eos87** [comment]
This is an old issue, will close it. Reopen if you feel like some more help is needed.
