### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by recoilstv** [liveblog/liveblog#1324]
Hello there! trying to install liveblog on ubuntu 16.04.7.

/var/www/liveblog/server# pip install -r requirements.txt

ERROR: Cannot install -r requirements.txt (line 16) and Flask==1.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested Flask==1.0
    superdesk-core 1.17.1 depends on flask<=0.12.2 and >=0.10.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

**Comment by agenceKanvas** [comment]
This is one of the errors I got here : https://github.com/liveblog/liveblog/issues/1323 
Did you found a fix ?

**Comment by eos87** [comment]
Hi. I'll take a look at this during the week and get back to you.

**Comment by recoilstv** [comment]
> Hi. I'll take a look at this and #1323 during the week and get back to you.

Thanks! I look forward to solving the problem!

**Comment by eos87** [comment]
Hi @recoilstv and @agenceKanvas, I found what the problem is. `pip` has changed the the way that it resolves dependency conflicts. So for the time being and give the complexity of Liveblog we need to stick to specific versions of `pip` and `setup tools` versions. I will be working in the next coming months into upgrading several dependencies in Liveblog but that would take time. 

For now please try the next commands (once you have activated your virtual environment):
```bash
pip install 'pip<=20.2.3'
pip install 'setuptools<50'
```

Then try installing the requirements once again (inside `server` folder) with: 
```bash
pip install -r requirements.txt
```

I hope that helps!

**Comment by recoilstv** [comment]
I managed to finish the installation as described in readme.txt, but an error occurs when trying to log in "Sorry, but can't reach the server now. Please try again later."

**Comment by eos87** [comment]
@recoilstv probably that's because of some missing environment variables. Try setting this variables in your local env (both client and server app)

```
export EMBED_PROTOCOL=http://
export LIVEBLOG_DEBUG='True'
export SUPERDESK_TESTING='False'
export BOTO_CONFIG=/doesnotexist
export SYNDICATION_VALIDATE_AUTH=0
export MAIL_SERVER='127.0.0.1'
export MAIL_PORT=1025
export MAIL_PASSWORD=__EMPTY__
export MAIL_USERNAME=__EMPTY__
export MAIL_USE_TLS=false
export MAIL_USE_SSL=false
export MAIL_SUPPRESS_SEND=False
export IFRAMELY_KEY=<INSERT_YOUR_KEY_HERE>
export OAUTHLIB_INSECURE_TRANSPORT='1'
export SUPERDESK_URL=http://127.0.0.1:5000/api
export SUPERDESK_CLIENT_URL=http://127.0.0.1:9000
```

**Comment by recoilstv** [comment]
"Try setting this variables in your local env (both client and server app)" - should I create .env.local files in the specified directories?
Here is such an error when logging in:
![login](https://user-images.githubusercontent.com/8203928/104593724-2404db00-5681-11eb-97d4-6b42f3531e90.png)

**Comment by eos87** [comment]
I normally put those variables in a `.env` file and then you need to run `source .env`. After that, run both client and server process (mind that the env vars have to be loaded in both terminals)

**Comment by recoilstv** [comment]
> I normally put those variables in a `.env` file and then you need to run `source .env`. After that, run both client and server process (mind that the env vars have to be loaded in both terminals)

"-bash: INSERT_YOUR_KEY_HERE: No such file or directory" after start source .env in /opt/liveblog/server

**Comment by eos87** [comment]
😅 sorry, that text was meant to be replaced by your `iframely` service key. https://iframely.com

**Comment by recoilstv** [comment]
> 😅 sorry, that text was meant to be replaced by your `iframely` service key. https://iframely.com

If I don't have this key, I can't start the service? The fact is that iframely.com requires money for registration

**Comment by eos87** [comment]
Indeed, it needs a paid license in order to make the embeds work but, it should start the service without it. Given that this is a very old issue, I will close it now. If you feel like providing a PR to improve something, please go ahead. We'll be glad to review it and merge it if possible.
