### ISSUE TITLE
elasticsearch errors in server

### ISSUE THREAD

**Issue by anibalpacheco** [liveblog/liveblog#1336]
I have the server running ok with Python 3.6.15

Elasticsearch server running ok in version "6.8.23"

Client running ok with node 10

Liveblog login ok with admin

But the server log this error related to elasticsearch:

```
05:29:10 rest.1 | elasticsearch.exceptions.TransportError: TransportError(406, 'Content-Type header [] is not supported')
05:29:10 rest.1 | HTTP Exception 500 has been raised: TransportError(406, 'Content-Type header [] is not supported')
05:29:10 rest.1 | ERROR:superdesk.errors:HTTP Exception 500 has been raised: TransportError(406, 'Content-Type header [] is not supported')
05:29:10 rest.1 | [2022-11-04 05:29:10 -0300] [10104] [ERROR] Error handling request /api/blogs?embedded=%7B%22original_creator%22:1%7D&sort=%5B(%22versioncreated%22,+-1)%5D&source=%7B%22query%22:%7B%22filtered%22:%7B%22filter%22:%7B%22term%22:%7B%22blog_status%22:%22open%22%7D%7D%7D%7D%7D
```

**Comment by anibalpacheco** [comment]
Solved!

I was installing a wrong version of elasticsearch, in Ubuntu 18.04 the correct line of the .list file is this:

```
deb [trusted=yes] http://packages.elastic.co/elasticsearch/1.7/debian stable main
```

Then, also may be needed for source installations (for me was) do the "curl POST" and the "rebuild" command that you indicate for the docker installation instructions.

**Comment by eos87** [comment]
Great! Thanks for letting us know that you guys found the problem. If you have further issues please let us know. 

Closing it.
