### ISSUE TITLE
Twitter embed preview vs post result in the real blog

### ISSUE THREAD

**Issue by anibalpacheco** [liveblog/liveblog#1337]
After set the iframe.ly key, I get the preview of a twitter embed or url working perfectly in the back-end, however, in the front-end of the blog (the feed that my site visitors will see), shows only the url of the tweet, do I need some extra configuration to obtain the same results? (tweet content, image, likes, etc) thank you. The compared screenshots examples below:

back-end:

![1669398905056](https://user-images.githubusercontent.com/89636/204036083-5a60cbb6-1786-43be-a302-de901aa434db.png)

front-end (public blog page):

![1669399043428](https://user-images.githubusercontent.com/89636/204036332-65ec1b0e-2031-4bce-8800-46da7df6798d.png)

**Comment by eos87** [comment]
Hi @anibalpacheco. There could be different reasons for this issue. How did you set the iframely key? Have you used an environment variable? If so, you need to make sure the client service reads this value from env vars before building it and running it. The same would be for backend. 
Another reason could be the theme. Are you using Default SEO Theme or a custom theme?

**Comment by anibalpacheco** [comment]
Hi @eos87 Yes, I'm using an env var in both, server and client, and using it to start server, to build & run the client.

Yes, I'm using the Default SEO Theme

**Comment by eos87** [comment]
@anibalpacheco could you then try running this `python manage.py register_local_themes` inside the `server/` folder? Make sure to also have the environment variables loaded. Please let me know if that goes well and fixes the issue.

**Comment by anibalpacheco** [comment]
@eos87 Executed the "register" with the env var loaded but nothing changed (grep output modified to hide the key value):

```
(liveblog) apacheco@liveblog:/srv/liveblog/server$ grep IFRAME env.local
IFRAMELY_KEY=...

(liveblog) apacheco@liveblog:/srv/liveblog/server$ source env.local && python3 manage.py register_local_themes
manage.py:6: ExtDeprecationWarning: Importing flask.ext.script is deprecated, use flask_script instead.
  from flask.ext.script import Manager
/opt/venv/pyenv/versions/3.6.15/envs/liveblog/lib/python3.6/site-packages/flask_cache/jinja2ext.py:33: ExtDeprecationWarning: Importing flask.ext.cache is deprecated, use flask_cache instead.
  from flask.ext.cache import make_template_fragment_key
Template file not found for angular theme.
WARNING:superdesk:Template file not found for angular theme.
5 themes registered
updated:
        * Liveblog 3 AMP Theme 3.4.13 (amp)
        * Liveblog 3 Default SEO Theme 3.6.52 (default)
        * Classic Theme 3.4.11 (classic)
        * Angular Liveblog Toolkit 3.4.8 (angular)
        * LB SEO Simple Theme 0.2.21 (simple)

```

**Comment by anibalpacheco** [comment]
@eos87 any suggestion? thank you

**Comment by anibalpacheco** [comment]
@eos87 Solved! Cloudflare Rocket Loader was the problem, disabled and now it shows the full embed with content and images

**Comment by eos87** [comment]
Hey @anibalpacheco, I'm sorry for my belated reply, I was out sick. I'm glad that you guys figured it out. I'll close this issue now. Thanks!
