### ISSUE TITLE
publicUrl is not set (demo)

### ISSUE THREAD

**Issue by cbenhagen** [liveblog/liveblog#329]
When running the demo the `publicUrl` is not set. So there is no way to view the themed output.

I am sorry if i miss something obvious here.

**Comment by Maria-Sourcefabric** [comment]
Zendesk Ticket #5266
"Our current demo was installed on a Ubuntu 15.10 running at digitalocean. In docker/common.yml we changed the SUPERDESK ENV variables to point to the actual IP of the host instead of 127.0.0.1 so we could login from anywhere on the net. Also the docker-local-create-user.sh script has been run. So far it is working as excpected. But now how are we supposed to render the blog entries using the template? After some digging I guessed that the publicUrl is not being set for some reason. I opened an already opened an issue on Github for this ( https://github.com/superdesk/liveblog/issues/329 ) I guess this somehow is more of a configuration issue on our side than a bug but without any real installation documentation it is hard to know what we are missing."

**Comment by actionless** [comment]
@cbenhagen please upload somewhere your edited common.yml and docker-compose-prebuilt.yml (if you've changed it or any other configs)

**Comment by cbenhagen** [comment]
@actionless the only lines changed are these in `common.yml`:
```yml
- SUPERDESK_URL=http://127.0.0.1/api
- SUPERDESK_WS_URL=ws://127.0.0.1/ws
- SUPERDESK_CLIENT_URL=http://127.0.0.1
```

where we changed `127.0.0.1` to the actual public ip.

**Comment by actionless** [comment]
where is that publicUrl which you mentioned is located? in the blog settings under the embed code?

i think the problem what you haven't set your amazon s3 credentials there:
https://github.com/superdesk/liveblog/blob/master/docker/common.yml#L44-L48

**Comment by cbenhagen** [comment]
I have seen it in liveblog/client/app/scripts/liveblog-edit/views/settings.html for example. Did not dig deep enough to find how it gets set.

Amazon s3 credentials? What are they needed for?

**Comment by actionless** [comment]
to publish the blog, i think atm there are no any local fallback, but @vied12 could asy for sure when he will be available

**Comment by actionless** [comment]
also you'll need http://embed.ly/ account for embedding different media types

**Comment by cbenhagen** [comment]
Oh I see. Yeah a local fallback would definitely make sense here. But as we really want to run it offline i will look for a local fake s3 provider.

**Comment by cbenhagen** [comment]
What about using https://hub.docker.com/r/fingershock/fakes3/ for the demo? This would need very little changes right? Actually we would only need an option to set the S3 endpoint to another container instead of amazon.

**Comment by actionless** [comment]
i think you'll have to edit `/etc/hosts` in order to mock s3

**Comment by actionless** [comment]
in `flask-s3` module there is an option `S3_BUCKET_DOMAIN`, but it won't be enough just adding it to `common.yml`, first you have to add it to the `settings.py` and rebuild Docker image then

**Comment by cbenhagen** [comment]
Another idea would be to set `FLASKS3_ACTIVE` to `False` right?

**Comment by actionless** [comment]
it looks like it want work then:
https://github.com/superdesk/liveblog/blob/master/server/liveblog/embed/embed.py#L69-L70

**Comment by cbenhagen** [comment]
This is what I came up with:
https://github.com/superdesk/liveblog/compare/master...cbenhagen:fake3s

But it still does not work. Any ideas?

**Comment by actionless** [comment]
have you tried putting here https://github.com/superdesk/liveblog/compare/master...cbenhagen:fake3s#diff-5160ec1132f19b75026c3dfc6a01f46eR49 equals instead of space between keys and values?

**Comment by cbenhagen** [comment]
Yes sorry. But `S3_BUCKET_DOMAIN` does still not seem to be used. Here is the Traceback:

```
superdesk_1 | 21:51:08 work.1 | Could not connect to the endpoint URL: "https://s3.local.amazonaws.com/fakes3_container/blogs/56be53c41ce27400a104c4d7/index.html" level=ERROR process=Worker-1
superdesk_1 | 21:51:08 work.1 | Traceback (most recent call last):
superdesk_1 | 21:51:08 work.1 |   File "/usr/local/lib/python3.4/dist-packages/celery/app/trace.py", line 240, in trace_task
superdesk_1 | 21:51:08 work.1 |     R = retval = fun(*args, **kwargs)
superdesk_1 | 21:51:08 work.1 |   File "/tmp/src/superdesk-core/superdesk/celery_app.py", line 113, in __call__
superdesk_1 | 21:51:08 work.1 |     return super().__call__(*args, **kwargs)
superdesk_1 | 21:51:08 work.1 |   File "/usr/local/lib/python3.4/dist-packages/celery/app/trace.py", line 438, in __protected_call__
superdesk_1 | 21:51:08 work.1 |     return self.run(*args, **kwargs)
superdesk_1 | 21:51:08 work.1 |   File "/opt/superdesk/liveblog/blogs/blogs.py", line 115, in publish_blog_embed_on_s3
superdesk_1 | 21:51:08 work.1 |     public_url = liveblog.embed.publish_embed(blog_id, '//%s/' % (app.config['SERVER_NAME']))
superdesk_1 | 21:51:08 work.1 |   File "/opt/superdesk/liveblog/embed/embed.py", line 73, in publish_embed
superdesk_1 | 21:51:08 work.1 |     app.media.delete(file_path)
superdesk_1 | 21:51:08 work.1 |   File "/tmp/src/superdesk-core/superdesk/storage/amazon/amazon_media_storage.py", line 153, in delete
superdesk_1 | 21:51:08 work.1 |     del_res = self.client.delete_object(Key=id_or_filename, Bucket=self.container_name)
superdesk_1 | 21:51:08 work.1 |   File "/usr/local/lib/python3.4/dist-packages/botocore/client.py", line 301, in _api_call
superdesk_1 | 21:51:08 work.1 |     return self._make_api_call(operation_name, kwargs)
superdesk_1 | 21:51:08 work.1 |   File "/usr/local/lib/python3.4/dist-packages/botocore/client.py", line 375, in _make_api_call
superdesk_1 | 21:51:08 work.1 |     operation_model, request_dict)
superdesk_1 | 21:51:08 work.1 |   File "/usr/local/lib/python3.4/dist-packages/botocore/endpoint.py", line 111, in make_request
superdesk_1 | 21:51:08 work.1 |     return self._send_request(request_dict, operation_model)
superdesk_1 | 21:51:08 work.1 |   File "/usr/local/lib/python3.4/dist-packages/botocore/endpoint.py", line 140, in _send_request
superdesk_1 | 21:51:08 work.1 |     success_response, exception):
superdesk_1 | 21:51:08 work.1 |   File "/usr/local/lib/python3.4/dist-packages/botocore/endpoint.py", line 206, in _needs_retry
superdesk_1 | 21:51:08 work.1 |     caught_exception=caught_exception)
superdesk_1 | 21:51:08 work.1 |   File "/usr/local/lib/python3.4/dist-packages/botocore/hooks.py", line 226, in emit
superdesk_1 | 21:51:08 work.1 |     return self._emit(event_name, kwargs)
superdesk_1 | 21:51:08 work.1 |   File "/usr/local/lib/python3.4/dist-packages/botocore/hooks.py", line 209, in _emit
superdesk_1 | 21:51:08 work.1 |     response = handler(**kwargs)
superdesk_1 | 21:51:08 work.1 |   File "/usr/local/lib/python3.4/dist-packages/botocore/retryhandler.py", line 183, in __call__
superdesk_1 | 21:51:08 work.1 |     if self._checker(attempts, response, caught_exception):
superdesk_1 | 21:51:08 work.1 |   File "/usr/local/lib/python3.4/dist-packages/botocore/retryhandler.py", line 250, in __call__
superdesk_1 | 21:51:08 work.1 |     caught_exception)
superdesk_1 | 21:51:08 work.1 |   File "/usr/local/lib/python3.4/dist-packages/botocore/retryhandler.py", line 273, in _should_retry
superdesk_1 | 21:51:08 work.1 |     return self._checker(attempt_number, response, caught_exception)
superdesk_1 | 21:51:08 work.1 |   File "/usr/local/lib/python3.4/dist-packages/botocore/retryhandler.py", line 313, in __call__
superdesk_1 | 21:51:08 work.1 |     caught_exception)
superdesk_1 | 21:51:08 work.1 |   File "/usr/local/lib/python3.4/dist-packages/botocore/retryhandler.py", line 222, in __call__
superdesk_1 | 21:51:08 work.1 |     return self._check_caught_exception(attempt_number, caught_exception)
superdesk_1 | 21:51:08 work.1 |   File "/usr/local/lib/python3.4/dist-packages/botocore/retryhandler.py", line 355, in _check_caught_exception
superdesk_1 | 21:51:08 work.1 |     raise caught_exception
superdesk_1 | 21:51:08 work.1 | botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://s3.local.amazonaws.com/fakes3_container/blogs/56be53c41ce27400a104c4d7/index.html"
superdesk_1 | 21:51:08 work.1 | Task liveblog.blogs.blogs.publish_blog_embed_on_s3[39e55278-1627-4db9-81b3-be2f3359e905] raised unexpected: EndpointConnectionError('Could not connect to the endpoint URL: "https://s3.local.amazonaws.com/fakes3_container/blogs/56be53c41ce27400a104c4d7/index.html"',) level=ERROR process=MainProcess
superdesk_1 | 21:51:08 work.1 | Traceback (most recent call last):
superdesk_1 | 21:51:08 work.1 |   File "/usr/local/lib/python3.4/dist-packages/celery/app/trace.py", line 240, in trace_task
superdesk_1 | 21:51:08 work.1 |     R = retval = fun(*args, **kwargs)
superdesk_1 | 21:51:08 work.1 |   File "/tmp/src/superdesk-core/superdesk/celery_app.py", line 113, in __call__
superdesk_1 | 21:51:08 work.1 |     return super().__call__(*args, **kwargs)
superdesk_1 | 21:51:08 work.1 |   File "/usr/local/lib/python3.4/dist-packages/celery/app/trace.py", line 438, in __protected_call__
superdesk_1 | 21:51:08 work.1 |     return self.run(*args, **kwargs)
superdesk_1 | 21:51:08 work.1 |   File "/opt/superdesk/liveblog/blogs/blogs.py", line 115, in publish_blog_embed_on_s3
superdesk_1 | 21:51:08 work.1 |     public_url = liveblog.embed.publish_embed(blog_id, '//%s/' % (app.config['SERVER_NAME']))
superdesk_1 | 21:51:08 work.1 |   File "/opt/superdesk/liveblog/embed/embed.py", line 73, in publish_embed
superdesk_1 | 21:51:08 work.1 |     app.media.delete(file_path)
superdesk_1 | 21:51:08 work.1 |   File "/tmp/src/superdesk-core/superdesk/storage/amazon/amazon_media_storage.py", line 153, in delete
superdesk_1 | 21:51:08 work.1 |     del_res = self.client.delete_object(Key=id_or_filename, Bucket=self.container_name)
superdesk_1 | 21:51:08 work.1 |   File "/usr/local/lib/python3.4/dist-packages/botocore/client.py", line 301, in _api_call
superdesk_1 | 21:51:08 work.1 |     return self._make_api_call(operation_name, kwargs)
superdesk_1 | 21:51:08 work.1 |   File "/usr/local/lib/python3.4/dist-packages/botocore/client.py", line 375, in _make_api_call
superdesk_1 | 21:51:08 work.1 |     operation_model, request_dict)
superdesk_1 | 21:51:08 work.1 |   File "/usr/local/lib/python3.4/dist-packages/botocore/endpoint.py", line 111, in make_request
superdesk_1 | 21:51:08 work.1 |     return self._send_request(request_dict, operation_model)
superdesk_1 | 21:51:08 work.1 |   File "/usr/local/lib/python3.4/dist-packages/botocore/endpoint.py", line 140, in _send_request
superdesk_1 | 21:51:08 work.1 |     success_response, exception):
superdesk_1 | 21:51:08 work.1 |   File "/usr/local/lib/python3.4/dist-packages/botocore/endpoint.py", line 206, in _needs_retry
superdesk_1 | 21:51:08 work.1 |     caught_exception=caught_exception)
superdesk_1 | 21:51:08 work.1 |   File "/usr/local/lib/python3.4/dist-packages/botocore/hooks.py", line 226, in emit
superdesk_1 | 21:51:08 work.1 |     return self._emit(event_name, kwargs)
superdesk_1 | 21:51:08 work.1 |   File "/usr/local/lib/python3.4/dist-packages/botocore/hooks.py", line 209, in _emit
superdesk_1 | 21:51:08 work.1 |     response = handler(**kwargs)
superdesk_1 | 21:51:08 work.1 |   File "/usr/local/lib/python3.4/dist-packages/botocore/retryhandler.py", line 183, in __call__
superdesk_1 | 21:51:08 work.1 |     if self._checker(attempts, response, caught_exception):
superdesk_1 | 21:51:08 work.1 |   File "/usr/local/lib/python3.4/dist-packages/botocore/retryhandler.py", line 250, in __call__
superdesk_1 | 21:51:08 work.1 |     caught_exception)
superdesk_1 | 21:51:08 work.1 |   File "/usr/local/lib/python3.4/dist-packages/botocore/retryhandler.py", line 273, in _should_retry
superdesk_1 | 21:51:08 work.1 |     return self._checker(attempt_number, response, caught_exception)
superdesk_1 | 21:51:08 work.1 |   File "/usr/local/lib/python3.4/dist-packages/botocore/retryhandler.py", line 313, in __call__
superdesk_1 | 21:51:08 work.1 |     caught_exception)
superdesk_1 | 21:51:08 work.1 |   File "/usr/local/lib/python3.4/dist-packages/botocore/retryhandler.py", line 222, in __call__
superdesk_1 | 21:51:08 work.1 |     return self._check_caught_exception(attempt_number, caught_exception)
superdesk_1 | 21:51:08 work.1 |   File "/usr/local/lib/python3.4/dist-packages/botocore/retryhandler.py", line 355, in _check_caught_exception
superdesk_1 | 21:51:08 work.1 |     raise caught_exception
superdesk_1 | 21:51:08 work.1 | botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://s3.local.amazonaws.com/fakes3_container/blogs/56be53c41ce27400a104c4d7/index.html"
```

**Comment by cbenhagen** [comment]
Found the culprit:
The endpoint is hardcoded in https://github.com/superdesk/superdesk-core/blob/master/superdesk/storage/amazon/amazon_media_storage.py#L63

**Comment by actionless** [comment]
my bad, was greping only liveblog repo, not superdesk-core, good find!
so is it working for you now?

**Comment by cbenhagen** [comment]
No, I am not sure how to fix it without breaking to much. I guess I will have to rely on you on this. For now I am in the process of creating an S3 account and so i can at least play with it already. Hopefully someone will step in and provide a nice way of running liveblog without S3.

**Comment by actionless** [comment]
@cbenhagen, btw, have you seen a message from @karelpetrak : https://forum.sourcefabric.org/discussion/comment/33936#Comment_33936

**Comment by cbenhagen** [comment]
Yes thank you :) We have been in touch and I have login credentials for the demo installation. Meanwhile I have a running instance of my own which has the advantage that we can change the template. Which is very important for the demo on Monday. For the real shoot I hope we will find a solution that works without the need of an internet connection. I will open a new issue to track this. Thank you for your help!

**Comment by cbenhagen** [comment]
Or should we just leave this one open and change the title?

**Comment by actionless** [comment]
yup, it could be changed to smth like "support configuring S3 storage base url as an env var"

**Comment by dzogrim** [comment]
@cbenhagen Hi! I think I've got the same pb as yours… does it mean it is required to have a S3 account to run and play with Live Blog? 'cause it seems running but never have embed code (read only)…

**Comment by actionless** [comment]
try to set `AMAZON_SERVER` env var:
https://github.com/superdesk/superdesk-core/blob/master/superdesk/factory/default_settings.py#L313

**Comment by dzogrim** [comment]
Thanks @actionless ; is it inevitable to have AWS S3 to use it correctly? Is there any documentation about working mandatory configuration? I add an S3 storage with the configuration but still not working correctly (only have an html without any live blog content inside).

**Comment by actionless** [comment]
yup, atm you need to have either real S3 account or any replacement service with compatible API

**Comment by dzogrim** [comment]
@actionless OK thanks!

**Comment by Juzzby** [comment]
Hi,

Contributing to this discussion: minio.io can be run locally or in production and provides a AWS S3 v4 or v2 compatible API

The current way superdesk handles the s3 url parsing means having DNS set up, can be virtualhost, is mandatory

Your url's to minio should look like this s3-<region>.<endpoint> and ssl (secure connection) should be turned off because minio currently does not support ssl while using virtual-hosted-style urls.

I hope this info will help someone some day, I for one have given up on using liveblog considering the installation process is such a drag. At this point it's easier to just develop my own liveblog clone than install sourcefabric's. That's something to consider..

ps: is there really any advantages for using virtual-hosted-style urls? because support for more options than just AWS would be very nice. Paying for AWS makes very little sense when you handle so little data it can easily reside on your own servers...

**Comment by nistormihai** [comment]
Hello,

I'm imported  in the discussion as well and sorry that I didn't participate till now.

The `public_url` is used with the `amazon-s3` for now, but the idea is that it could be used with other `storage providers` implementing different [MediaStorage](https://github.com/superdesk/superdesk-core/blob/master/superdesk/storage/amazon/amazon_media_storage.py#L80) extensions.

The `embed url` it is accessible, via `http://<SUPERDESK_URL>/embed/<BLOG_ID>`, (that is the server api url )
right now the url is only available if the instance is set on `debug` mode but that can be changed.
[getPublicUrl method](https://github.com/liveblog/liveblog/blob/master/client/app/scripts/liveblog-edit/blog.service.js#L37)


Regarding why are there any advantages for using  virtual-hosted-style urls:
* is that this embeds are high traffic so that is always best to cache static files and not to bother dealing with them.
* In the future we plan to have a SEO pre rendered content and that will also help with 
* ending and instance and still keeping the content.

Sorry to hear that the install process is that hard, we will try to address this.

PS: thanks about the `minio.io`
