### ISSUE TITLE
Password reset only accepts capitalized email address

### ISSUE THREAD

**Issue by psolbach** [liveblog/liveblog#365]
Hi team.

If a user was registered with a capitalized mail address, this is reflected in the saved string & admin interface. If this user then tries to receive a password reset mail without the exact capitalization, this results in a not-found error. Not sure this is entirely intentional?

Using all the latest releases of superdesk/liveblog.
Here's the log from Superdesk.

```
superdesk_1 | 09:55:05 rest.1 | WARNING:apps.auth.db.reset_password:User
password reset triggered with invalid email: xyz@foo.com
superdesk_1 | 09:55:05 rest.1 | ERROR:superdesk.errors:HTTP Exception
400 has been raised: Invalid email
```

**Comment by nistormihai** [comment]
it was a feature but It will get fix, because is email doesn't care about capitalization.

**Comment by psolbach** [comment]
OK, thanks.
