### ISSUE TITLE
Not responding on 443/HTTPS

### ISSUE THREAD

**Issue by dzogrim** [liveblog/liveblog#387]
Hi!
How is it possible to configure and run Liveblog's docker to serve **HTTPS** content only
  - on port 443 (yes, there's only the "443:443" line) ;
  - with signed/trusted certificates to be used ;

The setup works with "80:80" _http_ but not _https_ 
What parameters are needed and where? Help!

Thanks a lot in advance.
Regards

**Comment by dzogrim** [comment]
OK… since I added "things" to files 
  - docker/superdesk_vhost.conf
  - Dockerfile

I finally had a service behind port 443 in HTTPS, but… nothing is possible anymore. No login, no nothing :( is there any sample for HTTPS configuration of Liveblog ?

**Comment by nicolasbd** [comment]
+1

**Comment by omniton** [comment]
use nginx proxy: https://forum.sourcefabric.org/discussion/comment/34413#Comment_34413
