### ISSUE TITLE
Error during startup: waiting for mongo on mongodb:27017

### ISSUE THREAD

**Issue by fippu82** [liveblog/liveblog#460]
When following the instructions in the Readme file I always get this endless notification when starting the app using 
`./scripts/docker-local-demo.sh`:

`waiting for mongo on mongodb:27017`

And the app is not starting up. 

I have tried it on different OS, also with an Ubuntu 14.4, every time on a AWS EC2 instance. 

Best Regards, 
Philippe

**Comment by m0g** [comment]
Hi @fippu82,
if you are having issues with installing liveblog with docker, maybe you could try to install it locally https://github.com/liveblog/liveblog/blob/devel/README.md
