### ISSUE TITLE
s3 public urls dont work for me

### ISSUE THREAD

**Issue by shivno** [liveblog/liveblog#648]
hi,

i installed liveblog manually. i cant get the s3 public urls to work, 
from superdesk_core/superdesk/storage/amazon/amazon_media_storage.py generates an url like `http://bucketname.s3-us-east-1.amazonaws.com/`
but i only found that 
`http://s3.amazonaws.com/bucket_name/`
works. but surely i did something wrong, as nobody complained about it. i would like to document the manual install when everything works, for people who dont want docker in production. i use the 3.0.9 release.

**Comment by nistormihai** [comment]
Did you activate web site option in bucket properties?

**Comment by djbrd-sourcefabric** [comment]
I haven't tested this, but please try setting a couple of environment variables. Firstly, set AMAZON_URL_GENERATOR to 'partial', and set AMAZON_PROXY_SERVER to 's3.amazonaws.com'. The relevant code is actually in the Superdesk project.

**Comment by shivno** [comment]
thanks for responding!
@nistormihai i tried with and without i think.
@djbrd-sourcefabric ill do a complete reinstall anyway, because i messed with the code in the meantime, can test the next week. thanks. i know this is the wrong project, but superdesk-core had no issue tracker iirc. i was a bit confused with all your branches and forks between liveblog/superdesk maybe.

**Comment by djbrd-sourcefabric** [comment]
Yeah, it is a bit confusing.
We aim to remove the dependency on Superdesk in the not too distant future.

**Comment by nistormihai** [comment]
you shouldn't
you need to define bucket policy
to allow anonymous gets object

`{
    "Version": "2008-10-17",
    "Statement": [
        {
            "Sid": "AddPerm",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::<BUCKET_NAME>/*"
        }
    ]
}`

use `eu-west` region instead

**Comment by shivno** [comment]
installed it again and works now, thanks
