### ISSUE TITLE
API Errors

### ISSUE THREAD

**Issue by itwasmattgregg** [liveblog/liveblog#715]
When running the app via Docker I get these errors in my Chrome Console. 

```
WebSocket connection to 'ws://127.0.0.1/ws' failed: Connection closed before receiving a handshake response
GET http://127.0.0.1/api net::ERR_EMPTY_RESPONSE
```

The login page loads but the login won't respond. Some other info, I'm running this on an AWS ec2 instance and all the necessary ports are open as far as I know. Any assistance would be appreciated.

**Comment by masterxavierfox** [comment]
Ok so go to the following file
https://github.com/liveblog/liveblog/blob/master/docker/common.yml
and edit line 58,59,60 and replace localhost with the ip of your box. worked for me.
